/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL3.impl;

import fr.n7.pDL3.PDL3Package;
import fr.n7.pDL3.WorkDefinition;
import fr.n7.pDL3.WorkSequence;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getWorkDefinition <em>Work Definition</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getWorkSequence <em>Work Sequence</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessImpl extends MinimalEObjectImpl.Container implements fr.n7.pDL3.Process
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getWorkDefinition() <em>Work Definition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkDefinition()
   * @generated
   * @ordered
   */
  protected EList<WorkDefinition> workDefinition;

  /**
   * The cached value of the '{@link #getWorkSequence() <em>Work Sequence</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkSequence()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> workSequence;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL3Package.Literals.PROCESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL3Package.PROCESS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkDefinition> getWorkDefinition()
  {
    if (workDefinition == null)
    {
      workDefinition = new EObjectContainmentEList<WorkDefinition>(WorkDefinition.class, this, PDL3Package.PROCESS__WORK_DEFINITION);
    }
    return workDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getWorkSequence()
  {
    if (workSequence == null)
    {
      workSequence = new EObjectContainmentEList<WorkSequence>(WorkSequence.class, this, PDL3Package.PROCESS__WORK_SEQUENCE);
    }
    return workSequence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__WORK_DEFINITION:
        return ((InternalEList<?>)getWorkDefinition()).basicRemove(otherEnd, msgs);
      case PDL3Package.PROCESS__WORK_SEQUENCE:
        return ((InternalEList<?>)getWorkSequence()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        return getName();
      case PDL3Package.PROCESS__WORK_DEFINITION:
        return getWorkDefinition();
      case PDL3Package.PROCESS__WORK_SEQUENCE:
        return getWorkSequence();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        setName((String)newValue);
        return;
      case PDL3Package.PROCESS__WORK_DEFINITION:
        getWorkDefinition().clear();
        getWorkDefinition().addAll((Collection<? extends WorkDefinition>)newValue);
        return;
      case PDL3Package.PROCESS__WORK_SEQUENCE:
        getWorkSequence().clear();
        getWorkSequence().addAll((Collection<? extends WorkSequence>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PDL3Package.PROCESS__WORK_DEFINITION:
        getWorkDefinition().clear();
        return;
      case PDL3Package.PROCESS__WORK_SEQUENCE:
        getWorkSequence().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PDL3Package.PROCESS__WORK_DEFINITION:
        return workDefinition != null && !workDefinition.isEmpty();
      case PDL3Package.PROCESS__WORK_SEQUENCE:
        return workSequence != null && !workSequence.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ProcessImpl
