/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1.impl;

import fr.n7.pDL1.Occurrence;
import fr.n7.pDL1.PDL1Package;
import fr.n7.pDL1.Ressource;
import fr.n7.pDL1.WorkDefinition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Occurrence</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.impl.OccurrenceImpl#getOccurrence <em>Occurrence</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.OccurrenceImpl#getRessourceUtile <em>Ressource Utile</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.OccurrenceImpl#getWdAssociee <em>Wd Associee</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OccurrenceImpl extends MinimalEObjectImpl.Container implements Occurrence
{
  /**
   * The default value of the '{@link #getOccurrence() <em>Occurrence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOccurrence()
   * @generated
   * @ordered
   */
  protected static final int OCCURRENCE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getOccurrence() <em>Occurrence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOccurrence()
   * @generated
   * @ordered
   */
  protected int occurrence = OCCURRENCE_EDEFAULT;

  /**
   * The cached value of the '{@link #getRessourceUtile() <em>Ressource Utile</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRessourceUtile()
   * @generated
   * @ordered
   */
  protected Ressource ressourceUtile;

  /**
   * The cached value of the '{@link #getWdAssociee() <em>Wd Associee</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWdAssociee()
   * @generated
   * @ordered
   */
  protected WorkDefinition wdAssociee;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OccurrenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.OCCURRENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getOccurrence()
  {
    return occurrence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOccurrence(int newOccurrence)
  {
    int oldOccurrence = occurrence;
    occurrence = newOccurrence;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.OCCURRENCE__OCCURRENCE, oldOccurrence, occurrence));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ressource getRessourceUtile()
  {
    if (ressourceUtile != null && ressourceUtile.eIsProxy())
    {
      InternalEObject oldRessourceUtile = (InternalEObject)ressourceUtile;
      ressourceUtile = (Ressource)eResolveProxy(oldRessourceUtile);
      if (ressourceUtile != oldRessourceUtile)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.OCCURRENCE__RESSOURCE_UTILE, oldRessourceUtile, ressourceUtile));
      }
    }
    return ressourceUtile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ressource basicGetRessourceUtile()
  {
    return ressourceUtile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRessourceUtile(Ressource newRessourceUtile)
  {
    Ressource oldRessourceUtile = ressourceUtile;
    ressourceUtile = newRessourceUtile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.OCCURRENCE__RESSOURCE_UTILE, oldRessourceUtile, ressourceUtile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinition getWdAssociee()
  {
    if (wdAssociee != null && wdAssociee.eIsProxy())
    {
      InternalEObject oldWdAssociee = (InternalEObject)wdAssociee;
      wdAssociee = (WorkDefinition)eResolveProxy(oldWdAssociee);
      if (wdAssociee != oldWdAssociee)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.OCCURRENCE__WD_ASSOCIEE, oldWdAssociee, wdAssociee));
      }
    }
    return wdAssociee;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinition basicGetWdAssociee()
  {
    return wdAssociee;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWdAssociee(WorkDefinition newWdAssociee)
  {
    WorkDefinition oldWdAssociee = wdAssociee;
    wdAssociee = newWdAssociee;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.OCCURRENCE__WD_ASSOCIEE, oldWdAssociee, wdAssociee));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL1Package.OCCURRENCE__OCCURRENCE:
        return getOccurrence();
      case PDL1Package.OCCURRENCE__RESSOURCE_UTILE:
        if (resolve) return getRessourceUtile();
        return basicGetRessourceUtile();
      case PDL1Package.OCCURRENCE__WD_ASSOCIEE:
        if (resolve) return getWdAssociee();
        return basicGetWdAssociee();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL1Package.OCCURRENCE__OCCURRENCE:
        setOccurrence((Integer)newValue);
        return;
      case PDL1Package.OCCURRENCE__RESSOURCE_UTILE:
        setRessourceUtile((Ressource)newValue);
        return;
      case PDL1Package.OCCURRENCE__WD_ASSOCIEE:
        setWdAssociee((WorkDefinition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.OCCURRENCE__OCCURRENCE:
        setOccurrence(OCCURRENCE_EDEFAULT);
        return;
      case PDL1Package.OCCURRENCE__RESSOURCE_UTILE:
        setRessourceUtile((Ressource)null);
        return;
      case PDL1Package.OCCURRENCE__WD_ASSOCIEE:
        setWdAssociee((WorkDefinition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.OCCURRENCE__OCCURRENCE:
        return occurrence != OCCURRENCE_EDEFAULT;
      case PDL1Package.OCCURRENCE__RESSOURCE_UTILE:
        return ressourceUtile != null;
      case PDL1Package.OCCURRENCE__WD_ASSOCIEE:
        return wdAssociee != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (occurrence: ");
    result.append(occurrence);
    result.append(')');
    return result.toString();
  }

} //OccurrenceImpl
