/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurrence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.Occurrence#getOccurrence <em>Occurrence</em>}</li>
 *   <li>{@link fr.n7.pDL1.Occurrence#getRessourceUtile <em>Ressource Utile</em>}</li>
 *   <li>{@link fr.n7.pDL1.Occurrence#getWdAssociee <em>Wd Associee</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getOccurrence()
 * @model
 * @generated
 */
public interface Occurrence extends EObject
{
  /**
   * Returns the value of the '<em><b>Occurrence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occurrence</em>' attribute.
   * @see #setOccurrence(int)
   * @see fr.n7.pDL1.PDL1Package#getOccurrence_Occurrence()
   * @model
   * @generated
   */
  int getOccurrence();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Occurrence#getOccurrence <em>Occurrence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occurrence</em>' attribute.
   * @see #getOccurrence()
   * @generated
   */
  void setOccurrence(int value);

  /**
   * Returns the value of the '<em><b>Ressource Utile</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource Utile</em>' reference.
   * @see #setRessourceUtile(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getOccurrence_RessourceUtile()
   * @model
   * @generated
   */
  Ressource getRessourceUtile();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Occurrence#getRessourceUtile <em>Ressource Utile</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource Utile</em>' reference.
   * @see #getRessourceUtile()
   * @generated
   */
  void setRessourceUtile(Ressource value);

  /**
   * Returns the value of the '<em><b>Wd Associee</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wd Associee</em>' reference.
   * @see #setWdAssociee(WorkDefinition)
   * @see fr.n7.pDL1.PDL1Package#getOccurrence_WdAssociee()
   * @model
   * @generated
   */
  WorkDefinition getWdAssociee();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Occurrence#getWdAssociee <em>Wd Associee</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wd Associee</em>' reference.
   * @see #getWdAssociee()
   * @generated
   */
  void setWdAssociee(WorkDefinition value);

} // Occurrence
